### ISSUE TITLE
Client crash when deleting units

### ISSUE THREAD

**Issue by CheeseLord** [CheeseLord/warts#49]
```
Traceback (most recent call last):
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 52, in eventLoopTask
    self.doEvents()
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 46, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 105, in processEvent
    messenger.send(eventName)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 327, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 412, in __dispatch
    method (*(extraArgs + sentArgs))
  File "src/client/graphics.py", line 393, in handleMouseClick
    self.graphicsInterface.graphicsMessage(message.serialize())
  File "src/client/graphics_interface.py", line 163, in graphicsMessage
    self.backend.graphicsMessage(messageStr)
  File "src/client/backend.py", line 188, in graphicsMessage
    self.clearSelection()
  File "src/client/backend.py", line 265, in clearSelection
    self.graphicsInterface.backendMessage(msg.serialize())
  File "src/client/graphics_interface.py", line 144, in backendMessage
    gid = self.uidToGid[uid]
KeyError: (2, 15)
:task(error): Exception occurred in PythonTask eventManager
ERROR    main        Shutting down client due to unhandled exception in graphics code: 
Unhandled Error
Traceback (most recent call last):
  File "/home/spike/code/games/warts/venv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/spike/code/games/warts/venv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/home/spike/code/games/warts/venv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/spike/code/games/warts/venv/local/lib/python2.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/spike/code/games/warts/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/share/panda3d/direct/task/Task.py", line 467, in step
    self.mgr.poll()
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 52, in eventLoopTask
    self.doEvents()
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 46, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 105, in processEvent
    messenger.send(eventName)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 327, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 412, in __dispatch
    method (*(extraArgs + sentArgs))
  File "src/client/graphics.py", line 393, in handleMouseClick
    self.graphicsInterface.graphicsMessage(message.serialize())
  File "src/client/graphics_interface.py", line 163, in graphicsMessage
    self.backend.graphicsMessage(messageStr)
  File "src/client/backend.py", line 188, in graphicsMessage
    self.clearSelection()
  File "src/client/backend.py", line 265, in clearSelection
    self.graphicsInterface.backendMessage(msg.serialize())
  File "src/client/graphics_interface.py", line 144, in backendMessage
    gid = self.uidToGid[uid]
exceptions.KeyError: (2, 15)
```

**Comment by kronmillerg** [comment]
I believe the underlying problem here is that if a unit gets deleted from the server side, without going through the client GUI for `order_del`, then we don't remove it from the selection. So whenever someone next calls `clearSelection` (for example, when doing a simple left-click), the client tries to deselect units that don't exist, which causes this crash.

It's interesting that the units have been removed from the graphicsInterface's uid-to-gid mapping, though. That means that the client is definitely handling the deletes somewhere; I guess we're just not removing them from the selection.
