### ISSUE TITLE
Client should disconnect gracefully

### ISSUE THREAD

**Issue by JoelO** [CheeseLord/warts#58]
Error occurs when releasing drag on the close window box:

```
ERROR    main        Shutting down client due to unhandled exception in graphics code: 
Unhandled Error

Traceback (most recent call last):
  File "/usr/share/panda3d/direct/task/Task.py", line 470, in step
    self.mgr.poll()
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 52, in eventLoopTask
    self.doEvents()
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 46, in doEvents
    processFunc(self.eventQueue.dequeueEvent())
  File "/usr/share/panda3d/direct/showbase/EventManager.py", line 105, in processEvent
    messenger.send(eventName)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 327, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/usr/share/panda3d/direct/showbase/Messenger.py", line 412, in __dispatch
    method (*(extraArgs + sentArgs))
  File "src/client/graphics.py", line 454, in pandaEventMouseUp
    state.pos, self.getMousePos())
  File "src/client/graphics.py", line 507, in handleMouseDragEnd
    endPos = self.coordScreenTo3d(endPos)
  File "src/client/graphics.py", line 607, in coordScreenTo3d
    x, y = screenCoord
exceptions.TypeError: 'NoneType' object is not iterable
```

**Comment by JoelO** [comment]
Duplicate of #56
